package ru.finance.analyst.entity.yahoo

import ru.finance.analyst.entity.yahoo.{Price, SharesOutstanding}

case class YahooSummaryResponse(
//                                    defaultKeyStatistics: DefaultKeyStatistics,
                                    //                                    financialsTemplate: FinancialsTemplate,
                                                                        price: Price,
                                    //                                    financialData: FinancialData,
//                                                                        quoteType: QuoteType,
                                    //                                    calendarEvents: CalendarEvents,
//                                    summaryDetail: SummaryDetail,
//                                    symbol: String,
                                    //                                    pageViews: PageViews,
                                    //                                    quoteData: QuoteData,
                                    //                                    mktmData: Any
                                  )

case class Price(
//    quoteSourceName: String,
//    regularMarketOpen: SharesOutstanding,
//    averageDailyVolume3Month: SharesOutstanding,
//    exchange: String,
//    regularMarketTime: Int,
//    volume24Hr: Any,
//    regularMarketDayHigh: SharesOutstanding,
//    shortName: String,
//    averageDailyVolume10Day: SharesOutstanding,
//    longName: String,
//    regularMarketChange: SharesOutstanding,
//    currencySymbol: String,
//    regularMarketPreviousClose: SharesOutstanding,
//    postMarketTime: Int,
//    preMarketPrice: Any,
//    exchangeDataDelayedBy: Int,
//    toCurrency: String,
//    postMarketChange: SharesOutstanding,
//    postMarketPrice: SharesOutstanding,
//    exchangeName: String,
//    preMarketChange: Any,
//    circulatingSupply: Any,
//    regularMarketDayLow: SharesOutstanding,
//    priceHint: SharesOutstanding,
//    currency: String,
    regularMarketPrice: SharesOutstanding,
//    regularMarketVolume: SharesOutstanding,
//    lastMarket: String,
//    regularMarketSource: String,
//    openInterest: Any,
//    marketState: String,
//    underlyingSymbol: String,
//    marketCap: SharesOutstanding,
//    quoteType: String,
//    volumeAllCurrencies: Any,
//    postMarketSource: String,
//    strikePrice: Any,
//    symbol: String,
//    postMarketChangePercent: SharesOutstanding,
//    preMarketSource: String,
//    maxAge: Int,
//    fromCurrency: String,
//    regularMarketChangePercent: SharesOutstanding
)
