version: '3.2'
services:
  web:
    image: collatio
    ports:
      - "8080:8080"
    environment:
      - YAHOO_TOKEN=
      - TELEGRAM_TOKEN=
      - TELEGRAM_MAIN_ID=
      - ELASTIC_HOST=http://elasticsearch:9200
    links:
      - elasticsearch

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node

volumes:
  elasticsearch:
