ARG ELK_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/elasticsearch/elasticsearch:7.12.1@sha256:561bf27aa989803bfbac48ebd48e32daadb4215cf7940c599a62c13f225427fa

# Add your elasticsearch plugins setup here
# Example: RUN elasticsearch-plugin install analysis-icu
