package ru.finance.analyst.entity.yahoo

case class YahooStatisticsResponse(
                                    defaultKeyStatistics: DefaultKeyStatistics,
//                                    financialsTemplate: FinancialsTemplate,
//                                    price: Price,
//                                    financialData: FinancialData,
//                                    quoteType: QuoteType,
//                                    calendarEvents: CalendarEvents,
                                    summaryDetail: SummaryDetail,
                                    symbol: String,
//                                    pageViews: PageViews,
//                                    quoteData: QuoteData,
//                                    mktmData: Any
                                  )

case class Amrn(
    sourceInterval: Int,
    quoteSourceName: String,
    regularMarketOpen: SharesOutstanding,
    exchange: String,
    regularMarketTime: SharesOutstanding,
    fiftyTwoWeekRange: SharesOutstanding,
    sharesOutstanding: SharesOutstanding,
    regularMarketDayHigh: SharesOutstanding,
    shortName: String,
    longName: String,
    exchangeTimezoneName: String,
    regularMarketChange: SharesOutstanding,
    regularMarketPreviousClose: SharesOutstanding,
    fiftyTwoWeekHighChange: SharesOutstanding,
    exchangeTimezoneShortName: String,
    fiftyTwoWeekLowChange: SharesOutstanding,
    exchangeDataDelayedBy: Int,
    regularMarketDayLow: SharesOutstanding,
    priceHint: Int,
    currency: String,
    regularMarketPrice: SharesOutstanding,
    regularMarketVolume: SharesOutstanding,
    isLoading: Boolean,
    triggerable: Boolean,
    gmtOffSetMilliseconds: Int,
    firstTradeDateMilliseconds: Int,
    region: String,
    marketState: String,
    marketCap: SharesOutstanding,
    quoteType: String,
    invalid: Boolean,
    symbol: String,
    language: String,
    fiftyTwoWeekLowChangePercent: SharesOutstanding,
    regularMarketDayRange: SharesOutstanding,
    messageBoardId: String,
    fiftyTwoWeekHigh: SharesOutstanding,
    fiftyTwoWeekHighChangePercent: SharesOutstanding,
    uuid: String,
    market: String,
    fiftyTwoWeekLow: SharesOutstanding,
    regularMarketChangePercent: SharesOutstanding,
    fullExchangeName: String,
    tradeable: Boolean
)

//case class CalendarEvents(
//    maxAge: Int,
//    earnings: Earnings,
//    exDividendDate: Any,
//    dividendDate: Any
//)

case class DefaultKeyStatistics(
//    annualHoldingsTurnover: Any,
//    SharesOutstanding: SharesOutstanding,
//    beta3Year: Any,
    profitMargins: SharesOutstanding,
    enterpriseToEbitda: SharesOutstanding,
//    `52WeekChange`: SharesOutstanding,
//    morningStarRiskRating: Any,
    forwardEps: SharesOutstanding,
//    revenueQuarterlyGrowth: Any,
//    sharesOutstanding: SharesOutstanding,
//    fundInceptionDate: Any,
//    annualReportExpenseRatio: Any,
//    totalAssets: Any,
//    bookValue: SharesOutstanding,
//    sharesShort: SharesOutstanding,
//    sharesPercentSharesOut: SharesOutstanding,
//    fundFamily: String,
//    lastFiscalYearEnd: SharesOutstanding,
//    heldPercentInstitutions: SharesOutstanding,
//    netIncomeToCommon: SharesOutstanding,
    trailingEps: SharesOutstanding,
//    lastDividendValue: Any,
//    SandP52WeekChange: SharesOutstanding,
//    priceToBook: SharesOutstanding,
//    heldPercentInsiders: SharesOutstanding,
//    nextFiscalYearEnd: SharesOutstanding,
//    `yield`: Any,
//    mostRecentQuarter: SharesOutstanding,
//    shortRatio: SharesOutstanding,
//    sharesShortPreviousMonthDate: SharesOutstanding,
//    floatShares: SharesOutstanding,
    beta: SharesOutstanding,
//    enterpriseValue: SharesOutstanding,
//    priceHint: SharesOutstanding,
//    threeYearAverageReturn: Any,
//    lastSplitDate: SharesOutstanding,
//    lastSplitFactor: String,
//    legalType: String,
//    lastDividendDate: Any,
//    morningStarOverallRating: Any,
//    earningsQuarterlyGrowth: SharesOutstanding,
//    priceToSalesTrailing12Months: Any,
//    dateShortInterest: SharesOutstanding,
//    pegRatio: SharesOutstanding,
//    ytdReturn: Any,
//    forwardPE: SharesOutstanding,
//    maxAge: Int,
//    lastCapGain: Any,
//    shortPercentOfFloat: Any,
//    sharesShortPriorMonth: SharesOutstanding,
//    impliedSharesOutstanding: Any,
//    category: String,
//    fiveYearAverageReturn: Any
)

//case class Earnings(
//    earningsDate: Seq[SharesOutstanding],
//    earningsAverage: SharesOutstanding,
//    earningsLow: SharesOutstanding,
//    earningsHigh: SharesOutstanding,
//    revenueAverage: SharesOutstanding,
//    revenueLow: SharesOutstanding,
//    revenueHigh: SharesOutstanding
//)

//case class FinancialData(
//    ebitdaMargins: SharesOutstanding,
//    profitMargins: SharesOutstanding,
//    grossMargins: SharesOutstanding,
//    operatingCashflow: SharesOutstanding,
//    revenueGrowth: SharesOutstanding,
//    operatingMargins: SharesOutstanding,
//    ebitda: SharesOutstanding,
//    targetLowPrice: SharesOutstanding,
//    recommendationKey: String,
//    grossProfits: SharesOutstanding,
//    freeCashflow: SharesOutstanding,
//    targetMedianPrice: SharesOutstanding,
//    currentPrice: SharesOutstanding,
//    earningsGrowth: SharesOutstanding,
//    currentRatio: SharesOutstanding,
//    returnOnAssets: SharesOutstanding,
//    numberOfAnalystOpinions: SharesOutstanding,
//    targetMeanPrice: SharesOutstanding,
//    debtToEquity: SharesOutstanding,
//    returnOnEquity: SharesOutstanding,
//    targetHighPrice: SharesOutstanding,
//    totalCash: SharesOutstanding,
//    totalDebt: SharesOutstanding,
//    totalRevenue: SharesOutstanding,
//    totalCashPerShare: SharesOutstanding,
//    financialCurrency: String,
//    maxAge: Int,
//    revenuePerShare: SharesOutstanding,
//    quickRatio: SharesOutstanding,
//    recommendationMean: SharesOutstanding
//)

case class FinancialsTemplate(
    code: String,
    maxAge: Int
)

case class PageViews(
    shortTermTrend: String,
    midTermTrend: String,
    longTermTrend: String,
    maxAge: Int
)

//case class Price(
//    quoteSourceName: String,
//    regularMarketOpen: SharesOutstanding,
//    averageDailyVolume3Month: SharesOutstanding,
//    exchange: String,
//    regularMarketTime: Int,
//    volume24Hr: Any,
//    regularMarketDayHigh: SharesOutstanding,
//    shortName: String,
//    averageDailyVolume10Day: SharesOutstanding,
//    longName: String,
//    regularMarketChange: SharesOutstanding,
//    currencySymbol: String,
//    regularMarketPreviousClose: SharesOutstanding,
//    postMarketTime: Int,
//    preMarketPrice: Any,
//    exchangeDataDelayedBy: Int,
//    toCurrency: String,
//    postMarketChange: SharesOutstanding,
//    postMarketPrice: SharesOutstanding,
//    exchangeName: String,
//    preMarketChange: Any,
//    circulatingSupply: Any,
//    regularMarketDayLow: SharesOutstanding,
//    priceHint: SharesOutstanding,
//    currency: String,
//    regularMarketPrice: SharesOutstanding,
//    regularMarketVolume: SharesOutstanding,
//    lastMarket: String,
//    regularMarketSource: String,
//    openInterest: Any,
//    marketState: String,
//    underlyingSymbol: String,
//    marketCap: SharesOutstanding,
//    quoteType: String,
//    volumeAllCurrencies: Any,
//    postMarketSource: String,
//    strikePrice: Any,
//    symbol: String,
//    postMarketChangePercent: SharesOutstanding,
//    preMarketSource: String,
//    maxAge: Int,
//    fromCurrency: String,
//    regularMarketChangePercent: SharesOutstanding
//)

case class QuoteData(
    AMRN: Amrn
)

case class QuoteType(
    exchange: String,
    shortName: String,
    longName: String,
    exchangeTimezoneName: String,
    exchangeTimezoneShortName: String,
    isEsgPopulated: Boolean,
    gmtOffSetMilliseconds: String,
    quoteType: String,
    symbol: String,
    messageBoardId: String,
    market: String
)

case class SharesOutstanding(
    raw: Float,
    fmt: String,
//    longFmt: Option[String]
)

case class SummaryDetail(
//    previousClose: SharesOutstanding,
//    regularMarketOpen: SharesOutstanding,
//    twoHundredDayAverage: SharesOutstanding,
//    trailingAnnualDividendYield: Any,
//    payoutRatio: SharesOutstanding,
//    volume24Hr: Any,
//    regularMarketDayHigh: SharesOutstanding,
//    navPrice: Any,
//    averageDailyVolume10Day: SharesOutstanding,
//    totalAssets: Any,
//    regularMarketPreviousClose: SharesOutstanding,
//    fiftyDayAverage: SharesOutstanding,
//    trailingAnnualDividendRate: Any,
//    open: SharesOutstanding,
//    toCurrency: String,
//    averageVolume10days: SharesOutstanding,
//    expireDate: Any,
//    `yield`: Any,
//    algorithm: String,
//    dividendRate: Any,
//    exDividendDate: Any,
    beta: SharesOutstanding,
//    circulatingSupply: Any,
//    startDate: Any,
//    regularMarketDayLow: SharesOutstanding,
//    priceHint: SharesOutstanding,
//    currency: String,
//    regularMarketVolume: SharesOutstanding,
//    lastMarket: String,
//    maxSupply: Any,
//    openInterest: Any,
//    marketCap: SharesOutstanding,
//    volumeAllCurrencies: Any,
//    strikePrice: Any,
//    averageVolume: SharesOutstanding,
//    priceToSalesTrailing12Months: SharesOutstanding,
//    dayLow: SharesOutstanding,
//    ask: SharesOutstanding,
//    ytdReturn: Any,
//    askSize: SharesOutstanding,
//    volume: SharesOutstanding,
//    fiftyTwoWeekHigh: SharesOutstanding,
    forwardPE: SharesOutstanding,
//    maxAge: Int,
//    fromCurrency: String,
//    fiveYearAvgDividendYield: Any,
//    fiftyTwoWeekLow: SharesOutstanding,
//    bid: SharesOutstanding,
//    tradeable: Boolean,
//    dividendYield: Any,
//    bidSize: SharesOutstanding,
//    dayHigh: SharesOutstanding
)
